# Generated by Django 3.1.7 on 2021-03-27 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('open', models.FloatField(max_length=255)),
                ('high', models.CharField(max_length=255)),
                ('low', models.FloatField(max_length=255)),
                ('close', models.CharField(max_length=255)),
            ],
            options={
                'default_related_name': 'equities',
            },
        ),
    ]
