# Generated by Django 3.1.7 on 2021-03-27 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equity',
            name='code',
            field=models.IntegerField(),
        ),
    ]
